name: Maven CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@main

    - name: Set up JDK 21
      uses: actions/setup-java@main
      with:
        java-version: '21' # Change this to the required JDK version
        distribution: 'oracle' # Use Eclipse Temurin distribution
        cache: maven

    - name: Build with Maven
      run: mvn clean install
